export enum ConfigVars {
    APP_NAME = "APP_NAME",
    DB_HOST = "DB_HOST",
    DB_PORT = "DB_PORT",
    DB_USERNAME = "DB_USERNAME",
    DB_PASSWORD = "DB_PASSWORD",
    DB_NAME = "DB_NAME",
    JWT_ACCESS_TOKEN_PRIVATE_KEY = "JWT_ACCESS_TOKEN_PRIVATE_KEY",
    JWT_ACCESS_TOKEN_EXPIRATION_TIME = "JWT_ACCESS_TOKEN_EXPIRATION_TIME",
    MAILER_HOST = "MAILER_HOST",
    MAILER_USER = "MAILER_USER",
    MAILER_PASSWORD = "MAILER_PASSWORD",
    MAILER_FROM = "MAILER_FROM",
}
